<?php
$listA = array(
    'A-1' => true,
    'A-2' => true,
    'A-3' => true,
    'A-4' => true,
    'A-5' => true,
    'A-6' => true,
    'A-7' => true,
    'A-8' => true,
    'B-1' => true,
    'B-2' => true,
    'B-3' => true,
    'B-4' => true,
    'B-5' => true,
    'B-6' => true,
    'B-7' => true,
    'B-8' => true,
    'C-1' => true,
    'C-2' => true,
    'C-3' => true,
    'C-4' => true,
    'C-5' => true,
    'C-6' => true,
    'C-7' => true,
    'C-8' => true,
    'D-1' => true,
    'D-2' => true,
    'D-3' => true,
    'D-4' => true,
    'D-5' => true,
    'D-6' => true,
    'D-7' => true,
    'D-8' => true,
    'E-1' => true,
    'E-2' => true,
    'E-3' => true,
    'E-4' => true,
    'E-5' => true,
    'E-6' => true,
    'E-7' => true,
    'E-8' => true,
    'F-1' => true,
    'F-2' => true,
    'F-3' => true,
    'F-4' => true,
    'F-5' => true,
    'F-6' => true,
    'F-7' => true,
    'F-8' => true,
);
$listB = array(
    'A-1' => true,
    'A-2' => true,
    'A-3' => true,
    'A-6' => true,
    'A-7' => true,
    'A-8' => true,
    'B-1' => true,
    'B-2' => true,
    'B-3' => true,
    'B-4' => true,
    'B-5' => true,
    'B-6' => true,
    'B-7' => true,
    'B-8' => true,
    'C-1' => true,
    'C-2' => true,
    'C-3' => true,
    'C-4' => true,
    'C-5' => true,
    'C-6' => true,
    'C-7' => true,
    'C-8' => true,
    'D-1' => true,
    'D-2' => true,
    'D-3' => true,
    'D-4' => true,
    'D-5' => true,
    'D-6' => true,
    'D-7' => true,
    'D-8' => true,
    'E-1' => true,
    'E-2' => true,
    'E-3' => true,
    'E-4' => true,
    'E-5' => true,
    'E-6' => true,
    'E-7' => true,
    'E-8' => true,
);
$roomA = array(
    array(
        array('type' => 0, 'text' => ''),
        array('type' => 2, 'text' => ''),
        array('type' => 2, 'text' => 'ス'),
        array('type' => 2, 'text' => 'ク'),
        array('type' => 2, 'text' => 'リ'),
        array('type' => 2, 'text' => 'ー'),
        array('type' => 2, 'text' => 'ン'),
        array('type' => 2, 'text' => ''),
        array('type' => 2, 'text' => ''),
        array('type' => 0, 'text' => ''),
    ),
    array(
        array('type' => 0, 'text' => ''),
        array('type' => 0, 'text' => '1'),
        array('type' => 0, 'text' => '2'),
        array('type' => 0, 'text' => '3'),
        array('type' => 0, 'text' => '4'),
        array('type' => 0, 'text' => '5'),
        array('type' => 0, 'text' => '6'),
        array('type' => 0, 'text' => '7'),
        array('type' => 0, 'text' => '8'),
        array('type' => 0, 'text' => ''),
    ),
    array(
        array('type' => 0, 'text' => 'A'),
        array('type' => 1, 'text' => ''),
        array('type' => 1, 'text' => ''),
        array('type' => 1, 'text' => ''),
        array('type' => 1, 'text' => ''),
        array('type' => 1, 'text' => ''),
        array('type' => 1, 'text' => ''),
        array('type' => 1, 'text' => ''),
        array('type' => 1, 'text' => ''),
        array('type' => 0, 'text' => 'A'),
    ),
    array(
        array('type' => 0, 'text' => 'B'),
        array('type' => 1, 'text' => ''),
        array('type' => 1, 'text' => ''),
        array('type' => 1, 'text' => ''),
        array('type' => 1, 'text' => ''),
        array('type' => 1, 'text' => ''),
        array('type' => 1, 'text' => ''),
        array('type' => 1, 'text' => ''),
        array('type' => 1, 'text' => ''),
        array('type' => 0, 'text' => 'B'),
    ),
    array(
        array('type' => 0, 'text' => 'C'),
        array('type' => 1, 'text' => ''),
        array('type' => 1, 'text' => ''),
        array('type' => 1, 'text' => ''),
        array('type' => 1, 'text' => ''),
        array('type' => 1, 'text' => ''),
        array('type' => 1, 'text' => ''),
        array('type' => 1, 'text' => ''),
        array('type' => 1, 'text' => ''),
        array('type' => 0, 'text' => 'C'),
    ),
    array(
        array('type' => 0, 'text' => ''),
        array('type' => 0, 'text' => ''),
        array('type' => 0, 'text' => ''),
        array('type' => 0, 'text' => ''),
        array('type' => 0, 'text' => ''),
        array('type' => 0, 'text' => ''),
        array('type' => 0, 'text' => ''),
        array('type' => 0, 'text' => ''),
        array('type' => 0, 'text' => ''),
        array('type' => 0, 'text' => ''),
    ),
    array(
        array('type' => 0, 'text' => 'D'),
        array('type' => 1, 'text' => ''),
        array('type' => 1, 'text' => ''),
        array('type' => 1, 'text' => ''),
        array('type' => 1, 'text' => ''),
        array('type' => 1, 'text' => ''),
        array('type' => 1, 'text' => ''),
        array('type' => 1, 'text' => ''),
        array('type' => 1, 'text' => ''),
        array('type' => 0, 'text' => 'D'),
    ),
    array(
        array('type' => 0, 'text' => 'E'),
        array('type' => 1, 'text' => ''),
        array('type' => 1, 'text' => ''),
        array('type' => 1, 'text' => ''),
        array('type' => 1, 'text' => ''),
        array('type' => 1, 'text' => ''),
        array('type' => 1, 'text' => ''),
        array('type' => 1, 'text' => ''),
        array('type' => 1, 'text' => ''),
        array('type' => 0, 'text' => 'E'),
    ),
    array(
        array('type' => 0, 'text' => 'F'),
        array('type' => 1, 'text' => ''),
        array('type' => 1, 'text' => ''),
        array('type' => 1, 'text' => ''),
        array('type' => 1, 'text' => ''),
        array('type' => 1, 'text' => ''),
        array('type' => 1, 'text' => ''),
        array('type' => 1, 'text' => ''),
        array('type' => 1, 'text' => ''),
        array('type' => 0, 'text' => 'F'),
    ),

);
$roomB = array(
    array(
        array('type' => 0, 'text' => ''),
        array('type' => 2, 'text' => ''),
        array('type' => 2, 'text' => 'ス'),
        array('type' => 2, 'text' => 'ク'),
        array('type' => 2, 'text' => 'リ'),
        array('type' => 2, 'text' => 'ー'),
        array('type' => 2, 'text' => 'ン'),
        array('type' => 2, 'text' => ''),
        array('type' => 2, 'text' => ''),
        array('type' => 0, 'text' => ''),
    ),
    array(
        array('type' => 0, 'text' => ''),
        array('type' => 0, 'text' => '1'),
        array('type' => 0, 'text' => '2'),
        array('type' => 0, 'text' => '3'),
        array('type' => 0, 'text' => '4'),
        array('type' => 0, 'text' => '5'),
        array('type' => 0, 'text' => '6'),
        array('type' => 0, 'text' => '7'),
        array('type' => 0, 'text' => '8'),
        array('type' => 0, 'text' => ''),
    ),
    array(
        array('type' => 0, 'text' => 'A'),
        array('type' => 1, 'text' => ''),
        array('type' => 1, 'text' => ''),
        array('type' => 1, 'text' => ''),
        array('type' => 0, 'text' => ''),
        array('type' => 0, 'text' => ''),
        array('type' => 1, 'text' => ''),
        array('type' => 1, 'text' => ''),
        array('type' => 1, 'text' => ''),
        array('type' => 0, 'text' => 'A'),
    ),
    array(
        array('type' => 0, 'text' => 'B'),
        array('type' => 1, 'text' => ''),
        array('type' => 1, 'text' => ''),
        array('type' => 1, 'text' => ''),
        array('type' => 1, 'text' => ''),
        array('type' => 1, 'text' => ''),
        array('type' => 1, 'text' => ''),
        array('type' => 1, 'text' => ''),
        array('type' => 1, 'text' => ''),
        array('type' => 0, 'text' => 'B'),
    ),
    array(
        array('type' => 0, 'text' => 'C'),
        array('type' => 1, 'text' => ''),
        array('type' => 1, 'text' => ''),
        array('type' => 1, 'text' => ''),
        array('type' => 1, 'text' => ''),
        array('type' => 1, 'text' => ''),
        array('type' => 1, 'text' => ''),
        array('type' => 1, 'text' => ''),
        array('type' => 1, 'text' => ''),
        array('type' => 0, 'text' => 'C'),
    ),
    array(
        array('type' => 0, 'text' => 'D'),
        array('type' => 1, 'text' => ''),
        array('type' => 1, 'text' => ''),
        array('type' => 1, 'text' => ''),
        array('type' => 1, 'text' => ''),
        array('type' => 1, 'text' => ''),
        array('type' => 1, 'text' => ''),
        array('type' => 1, 'text' => ''),
        array('type' => 1, 'text' => ''),
        array('type' => 0, 'text' => 'D'),
    ),
    array(
        array('type' => 0, 'text' => 'E'),
        array('type' => 1, 'text' => ''),
        array('type' => 1, 'text' => ''),
        array('type' => 1, 'text' => ''),
        array('type' => 1, 'text' => ''),
        array('type' => 1, 'text' => ''),
        array('type' => 1, 'text' => ''),
        array('type' => 1, 'text' => ''),
        array('type' => 1, 'text' => ''),
        array('type' => 0, 'text' => 'E'),
    ),
);
